---
#######
# All #
#######

# just for debug.
debug_mode: false

# allow_url_fopen
#   Default Value: On
php_allow_url_fopen: "On"
php_disable_functions: "exec,passthru,shell_exec,system,popen"
php_display_errors: "Off"
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_memory_limit: "1024M"
php_opcache_enable: 1
php_opcache_revalidate_freq: 0
php_post_max_size: "20M"
php_serialize_precision: 17
php_session_cookie_httponly: 1
php_session_use_strict_mode: 1
php_soap_wsdl_cache_dir: '/php/cache/wsdl'
php_timezone: "America/Los_Angeles"
php_upload_max_filesize: "20M"
php_upload_tmp_dir: "/php/cache/upload_tmp"


##########
# CentOS #
##########

yum_php_version: "70u"
yum_php_packages:
  - php{{ yum_php_version }}-cli
  - php{{ yum_php_version }}-common
  - php{{ yum_php_version }}-fpm
  - php{{ yum_php_version }}-fpm-nginx
  - php{{ yum_php_version }}-json
  - php{{ yum_php_version }}-mysqlnd
  - php{{ yum_php_version }}-opcache
  - php{{ yum_php_version }}-pdo
  - php{{ yum_php_version }}-mbstring
  - php{{ yum_php_version }}-gd

# PHP-FPM FastCGI.
centos_php_fastcgi_listen: "/run/php-fpm/www.sock"
centos_nginx_fastcgi_server: "unix:{{ centos_php_fastcgi_listen }}"

