---
################################################################################
# Deploy PHP 7 (php-fpm) for Nginx on CentOS. (forked from itcraftsmanpl.php7)
# Source: https://galaxy.ansible.com/chusiang/php7/
################################################################################
# Note: proc_open will be enabled on chap-press for wordpress cli access & other plugins.
# https://github.com/chapmanu/chap-press/pull/7#issuecomment-324784310
################################################################################

# before install.
- name: Install requires package for use yum module
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"

- name: Install epel from remote repo on CentOS 7
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution_major_version == "7"

- name: Install remi from remote repo on CentOS 7
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present
  when: ansible_distribution_major_version == "7"

- name: get ius repo install script
  get_url: url=https://setup.ius.io/ dest=/tmp/setup-ius.sh

- name: Install ius from remote repo
  command: bash /tmp/setup-ius.sh

# Upgrade all packages.
- name: upgrade all packages
  yum: name=* state=latest

# Install PHP7 packages.
- name: Install PHP Packages
  yum: name={{ item }} enablerepo=ius state=present
  with_nested: "{{ yum_php_packages }}"
  when: yum_php_packages is defined
  notify: restart php7-fpm on centos

- debug: msg="=> Enter configure stage"

- stat: path=/etc/php-fpm.conf
  register: phpfpm_centos

- include: php-fpm-centos.yml
  when: phpfpm_centos.stat.exists


